g++ \
Lands/TileTypes/Barn.cpp \
Lands/TileTypes/Grassland.cpp \
Lands/TileTypes/Coop.cpp \
Facilities/FacilityTypes/Mixer.cpp \
Facilities/FacilityTypes/Well.cpp \
Facilities/FacilityTypes/Truck.cpp \
Animals/FarmAnimal.cpp \
Animals/Pig.cpp \
Animals/Chicken.cpp \
Animals/MeatProducing.cpp \
Animals/EggProducing.cpp \
cells.cpp \
-o engiMoonEXE
